services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5432:3306'
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql


  web:
    build: .
    # restart: always
    working_dir: /app
    # network_mode: host

    # command: sh -c "python /app/manage.py runserver 0.0.0.0:8000"
    command: sh -c "python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    
    ports:  
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy
    
# Names our volume
volumes:
  my-db:
