# Generated by Django 5.0.7 on 2024-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='ADMIN', max_length=50),
        ),
    ]
