# Generated by Django 5.0.7 on 2024-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_date_event_time_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField()),
                ('user', models.IntegerField()),
                ('action', models.CharField(choices=[('post', 'Post'), ('put', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('organizer', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
