# Generated by Django 5.0.7 on 2024-07-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_pendingevents_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventapproval',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='eventapproval',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='pendingevents',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventapproval',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
