# Generated by Django 5.0.7 on 2024-07-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_event_eventapproval_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapproval',
            name='approved',
            field=models.BooleanField(default=models.NullBooleanField(verbose_name='')),
        ),
    ]
