# Generated by Django 5.0.7 on 2024-07-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventapproval_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapproval',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
