# Generated by Django 5.0.7 on 2024-07-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventapproval_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapproval',
            name='approved',
        ),
    ]
