# Generated by Django 5.0.7 on 2024-07-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_eventapproval_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapproval',
            name='hi',
            field=models.IntegerField(default=1),
        ),
    ]
