# Generated by Django 5.0.7 on 2024-07-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventapproval_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapproval',
            name='hi',
        ),
    ]
