# Generated by Django 5.0.7 on 2024-07-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
        ('events', '0017_eventapproval_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
