# Generated by Django 5.0.7 on 2024-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_attendees_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapproval',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
